### PR TITLE
plugincontainer: use docker v27

### LINKED ISSUE #135: Upgrading the docker/docker package to v27.2.0
**Is your feature request related to a problem? Please describe.**

I am having issues with importing `go-secure-stdlib/plugincontainer`: 
I need to use a newer version of `docker/docker` (v27.1.1), but the deprecated type `ListImageOptions` was removed in v27.0.0 because of the change https://github.com/moby/moby/pull/47900, so plugincontainer will have the undefined error
```
# github.com/hashicorp/go-secure-stdlib/plugincontainer
../../../../pkg/mod/github.com/hashicorp/go-secure-stdlib/plugincontainer@v0.3.1-0.20240801143802-fab9dfbe9dbc/container_runner_linux.go:180:54: undefined: types.ImageListOptions
```
Similar to https://github.com/hashicorp/go-secure-stdlib/pull/126

**Describe the solution you'd like**

Upgrading `docker/docker` and resolve conflicts

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by tvoran**
Replace types.ImageListOptions with image.ListOptions, update docker and otlptracehttp to latest.

```
go get github.com/docker/docker@latest
go get go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp@latest
go mod tidy
```

Fixes #135

### CODE REVIEW

**Review by AndyYan007 — APPROVED** [review]
Thanks for the quick fix!

**Comment by AndyYan007** [comment]
Do we have an ETA when this change can be merged and released? Confluent has some services with dependency on this change.

**Comment by AndrewYinLi** [comment]
@sgmiller Any ETA on this?

**Comment by AndrewYinLi** [comment]
@tvoran Is it possible to merge with just one review?

**Comment by tvoran** [comment]
Tagged [plugincontainer/v0.4.1](https://github.com/hashicorp/go-secure-stdlib/releases/tag/plugincontainer%2Fv0.4.1)

**Pull request merged**
