### PR TITLE
plugincontainer: updating go deps

### PR DESCRIPTION
**Pull request by tvoran**
Bumping go-hclog, go-plugin, x/sys, grpc, and protobuf to follow on to #126.

Also bumped otlptracehttp@latest to avoid ambiguous imports downstream.

(I think after these changes we're ready to tag v0.4.0, then along with https://github.com/hashicorp/vault-testing-stepwise/pull/17 we should be able to update `vault` and `vault/sdk` to docker@v26.)

### CODE REVIEW

**Review by Zlaticanin — APPROVED** [review]

**Comment by vinay-gopalan** [comment]
Looks good! Wanted to confirm: if the plan is to do a `v0.4.0` release, should these changes be merged into the `v0` branch instead of `main`? If they are going directly into `main`, are we backporting them to the `v0` branch for the release?

**Comment by pulkits15** [comment]
Hi, any ETA by when this will be merged and released? Is this blocked on waiting?

**Comment by tvoran** [comment]
@johanbrandhorst I don't have merge permissions here, maybe you still do?

**Comment by johanbrandhorst** [comment]
Happy to help, not sure who could help give you the permission 😬

**Pull request merged**
