### PR TITLE
chore(deps): Update aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by hugoghx**
Important: Due to underlying changes in the SDK, awsutil/v2 will no
longer automatically load the "default" AWS shared profile if none is
provided. To load a shared profile, you'll need to set the AWS_PROFILE
env var.

---

After merging this PR, a new `awsutil/v2.1.0` tag and GitHub release will be created.

### CODE REVIEW

**Review by ddebko — APPROVED** [review]
The plugin container job is failing, you might just need to rerun it?
The error looks strange:
```
TestExamplePlugin/runsc/simulated_plugin_error: plugin shut down with non-0 exit code
```

**Comment by hugoghx** [comment]
> The plugin container job is failing, you might just need to rerun it? The error looks strange:
> 
> ```
> TestExamplePlugin/runsc/simulated_plugin_error: plugin shut down with non-0 exit code
> ```

Yeah, I re-ran it once and it just failed again. Currently looking into this - I think it's unlikely that these changes are making it fail though

**Comment by hugoghx** [comment]
Adding @jefferai as we need an authorised user to approve these changes

**Comment by hugoghx** [comment]
I wasn't able to find much on why `plugincontainer` is failing. I re-ran it once more and it failed again - My only guess here is that something changed in the dependencies we use to run that test, given that we always pull `latest` for some of them.

I've also noticed, looking at all the [actions](https://github.com/hashicorp/go-secure-stdlib/actions), that this is the case for other PRs, and the only `plugincontainer` test that has passed was 4 months ago with the last merge to `main`. 

There's also some PRs targeting `plugincontainer` https://github.com/hashicorp/go-secure-stdlib/pull/126 https://github.com/hashicorp/go-secure-stdlib/pull/125 https://github.com/hashicorp/go-secure-stdlib/pull/123

**Review by johanbrandhorst — APPROVED** [review]

**Comment by louisruch** [comment]
Oh I see @hugoghx tried to do this a while ago, I am closing this in favor of #143

**Pull request closed without merging**
